# Generated by Django 5.1.7 on 2025-03-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Итальянская', 'Итальянская'), ('Японская', 'Японская'), ('Фастфуд', 'Фастфуд')], max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
    ]
