# Generated by Django 5.1.7 on 2025-04-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_fooditem_name_alter_fooditem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
    ]
